[project]
name = "Chanakya"
version = "0.1.0"  # Add this line with your desired version number
description = "A fully local chatbot"
authors = [
    {name = "Rishabh Bajpai", email = "rishabhbajpai24@gmail.com"},
]
requires-python = "==3.12.2"
dependencies = [
    "nest_asyncio",
    "requests",
    "torchaudio",
    "chatterbox-tts",
    "flask",
    "flask_cors",
    "langchain_ollama",
    "langchain",
    "langchain_mcp_adapters",
    "flask[async]"
]

[build-system]
requires = ["uv"]
build-backend = "uv"
