name: 👋 Welcome Bot

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome new contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hi there, welcome to **Chanakya-Local-Friend**!  
            Thanks for opening your first issue 🎉  

            🔹 Please read our [Contributing Guide](https://github.com/Rishabh-Bajpai/Chanakya-Local-Friend/blob/main/docs/contributing.md).  
            🔹 If you’re new, check out our [Good First Issue Guide](https://github.com/Rishabh-Bajpai/Chanakya-Local-Friend/blob/main/docs/good_first_issue.md).  

            We're excited to have you here 🚀!
          pr-message: |
            👋 Hi there, thanks for your first Pull Request to **Chanakya-Local-Friend**! 🎉  

            ✅ Please make sure:
            - You followed the [Contributing Guide](https://github.com/Rishabh-Bajpai/Chanakya-Local-Friend/blob/main/docs/contributing.md)  
            - You linked the issue this PR closes (if applicable)  
            - Your changes are well-documented  

            We’ll review your PR soon. Welcome to the community! 💙
